### ISSUE TITLE
有时候需要使用popToViewController，pop到指定的控制器，可以增加这个方法吗？

### ISSUE THREAD

**Issue by yangzhixiao** [CoderLT/ATNavigationController#1]
我看你的代码是根据控制器的内存地址来保存截图的，那我pop到指定的控制器后，就没有清除掉之前最后一个控制器的截图，这样一来会造成内存泄露，可以增加这个popToViewController方法相应的处理吗？谢谢

**Comment by yangzhixiao** [comment]
我发现改起来很简单，所以就pull request了

**Comment by CoderLT** [comment]
相关功能我已经更新处理, 你可以更新库pod update.  -> ATNavigationController (0.0.13)

ps: 你的pull request有不够完善的地方, 所以我自己更新了.
